Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -6,29 +6,10 @@
 
 # Corresponding video series: https://category5.tv/feature/minecraft
 
-# GNU GENERAL PUBLIC LICENSE
-# Version 3, 29 June 2007
-#
-# Copyright (C) 2021-2024 Robbie Ferguson (Category5.TV)
-#
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, either version 3 of the License, or
-# (at your option) any later version.
-#
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <https://www.gnu.org/licenses/>.
-#
-
-pcver="4.1"
+pcver="3.7"
 
 if [[ $EUID -ne 0 ]]; then
-  echo "ERROR: This script must be run as root. Try: sudo $0" 2>&1
+  echo "ERROR: This script must be run as root" 2>&1
   exit 1
 fi
 
@@ -120,7 +101,7 @@ dialog --title "Pinecraft Installer $pcver" \
 dialog --infobox "Checking dependencies..." 3 34 ; sleep 2
 
 javaminver=8; # The minimum version of Java for Minecraft Server to run
-javamaxver=21; # The current max version available in known repositories that Minecraft Server can run on.
+javamaxver=17; # The current max version available in known repositories that Minecraft Server can run on.
 
 if [[ $updated == 0 ]]; then
   dialog --infobox "Updating repositories..." 3 34 ;
@@ -254,19 +235,11 @@ if [ $(dpkg-query -W -f='${Status}' cron 2>/dev/null | grep -c "ok installed") -
   apt-get -y install cron > /dev/null 2>&1
 fi
 
-mcver="1.16.5" # Set a default old version
-if (( $ver >= 21 )); then # Java version 21+ allows 1.20.6+
-  mcver="1.21"
-elif (( $ver >= 17 )); then # Java version 17+ allows 1.18.x-1.20.4
-  mcver="1.20.4"
+mcver="1.16.5"
+if (( $ver >= 17 )); then # Java version 17+ allows 1.18.x
+  mcver="1.20.1"
 elif (( $ver >= 16 )); then # Java version 16+ allows 1.17.x
   mcver="1.17.1"
-fi
-
-if (( $ver < 21 )); then
-dialog --title "Java $ver" --msgbox "
-Your installed version of Java ($ver) can only support up to Minecraft $mcver. To install a newer version of Minecraft, please see the Pinecraft documentation to obtain the recommended Base OS.
-" 12 48
 fi
 
 # Username may be provided on CLI as in 1.0
@@ -475,16 +448,7 @@ fi
 
 
 # https://www.minecraft.net/en-us/download/server
-# https://mcversions.net/
-if [[ $mcver == "1.21" ]]; then
-  vanilla="https://piston-data.mojang.com/v1/objects/450698d1863ab5180c25d7c804ef0fe6369dd1ba/server.jar"
-elif [[ $mcver == "1.20.6" ]]; then
-  vanilla="https://piston-data.mojang.com/v1/objects/145ff0858209bcfc164859ba735d4199aafa1eea/server.jar"
-elif [[ $mcver == "1.20.4" ]]; then
-  vanilla="https://piston-data.mojang.com/v1/objects/8dd1a28015f51b1803213892b50b7b4fc76e594d/server.jar"
-elif [[ $mcver == "1.20.2" ]]; then
-  vanilla="https://piston-data.mojang.com/v1/objects/5b868151bd02b41319f54c8d4061b8cae84e665c/server.jar"
-elif [[ $mcver == "1.20.1" ]]; then
+if [[ $mcver == "1.20.1" ]]; then
   vanilla="https://piston-data.mojang.com/v1/objects/84194a2f286ef7c14ed7ce0090dba59902951553/server.jar"
 elif [[ $mcver == "1.19.4" ]]; then
   vanilla="https://piston-data.mojang.com/v1/objects/8f3112a1049751cc472ec13e397eade5336ca7ae/server.jar"
@@ -514,7 +478,7 @@ flavor=""
 
 declare -a flavors=()
 
-if [[ $mcverANY == "1" ]] || [[ $mcver == "1.17.1" ]] || [[ $mcver == "1.17" ]] || [[ $mcver == "1.16.5" ]] || [[ $mcver == "1.18" ]] || [[ $mcver == "1.18.1" ]] || [[ $mcver == "1.18.2" ]] || [[ $mcver == "1.19" ]] || [[ $mcver == "1.19.2" ]] || [[ $mcver == "1.19.3" ]] || [[ $mcver == "1.19.4" ]] || [[ $mcver == "1.20.1" ]] || [[ $mcver == "1.20.2" ]] || [[ $mcver == "1.20.4" ]] || [[ $mcver == "1.20.6" ]] || [[ $mcver == "1.21" ]]; then
+if [[ $mcverANY == "1" ]] || [[ $mcver == "1.17.1" ]] || [[ $mcver == "1.17" ]] || [[ $mcver == "1.16.5" ]] || [[ $mcver == "1.18" ]] || [[ $mcver == "1.18.1" ]] || [[ $mcver == "1.18.2" ]] || [[ $mcver == "1.19" ]] || [[ $mcver == "1.19.2" ]] || [[ $mcver == "1.19.3" ]] || [[ $mcver == "1.19.4" ]] || [[ $mcver == "1.20.1" ]]; then
   flavors+=("P" "Paper (Default, ${mcver})")
 fi
 
@@ -523,7 +487,7 @@ if [[ $mcverANY == "1" ]] || [ $(version $mcver) -ge $(version "1.14.0") ]; then
   flavors+=("F" "Fabric (${mcver})")
 fi
 
-if [[ $mcverANY == "1" ]] || [[ $mcver == "1.16.5" ]] || [[ $mcver == "1.17.1" ]] || [[ $mcver == "1.18" ]] || [[ $mcver == "1.18.1" ]] || [[ $mcver == "1.18.2" ]] || [[ $mcver == "1.19" ]] || [[ $mcver == "1.19.2" ]] || [[ $mcver == "1.19.3" ]] || [[ $mcver == "1.19.4" ]] || [[ $mcver == "1.20.1" ]] || [[ $mcver == "1.20.2" ]] || [[ $mcver == "1.20.4" ]] || [[ $mcver == "1.20.6" ]] || [[ $mcver == "1.21" ]]; then
+if [[ $mcverANY == "1" ]] || [[ $mcver == "1.16.5" ]] || [[ $mcver == "1.17.1" ]] || [[ $mcver == "1.18" ]] || [[ $mcver == "1.18.1" ]] || [[ $mcver == "1.18.2" ]] || [[ $mcver == "1.19" ]] || [[ $mcver == "1.19.2" ]] || [[ $mcver == "1.19.3" ]] || [[ $mcver == "1.19.4" ]] || [[ $mcver == "1.20.1" ]]; then
   flavors+=("R" "Forge (${mcver})")
 fi
 
@@ -537,7 +501,7 @@ if [[ $mcverANY == "1" ]] || [[ $mcver == "1.12.2" ]]; then
   flavors+=("C" "Cuberite (1.12)")
 fi
 
-if [[ $mcverANY == "1" ]] || [[ $mcver == "1.17.1" ]] || [[ $mcver == "1.17" ]] || [[ $mcver == "1.16.5" ]] || [[ $mcver == "1.18" ]] || [[ $mcver == "1.18.1" ]] || [[ $mcver == "1.18.2" ]] || [[ $mcver == "1.19" ]] || [[ $mcver == "1.19.2" ]] || [[ $mcver == "1.19.3" ]] || [[ $mcver == "1.19.4" ]] || [[ $mcver == "1.20.1" ]] || [[ $mcver == "1.20.2" ]] || [[ $mcver == "1.20.4" ]] || [[ $mcver == "1.20.6" ]] || [[ $mcver == "1.21" ]]; then
+if [[ $mcverANY == "1" ]] || [[ $mcver == "1.17.1" ]] || [[ $mcver == "1.17" ]] || [[ $mcver == "1.16.5" ]] || [[ $mcver == "1.18" ]] || [[ $mcver == "1.18.1" ]] || [[ $mcver == "1.18.2" ]] || [[ $mcver == "1.19" ]] || [[ $mcver == "1.19.2" ]] || [[ $mcver == "1.19.3" ]] || [[ $mcver == "1.19.4" ]] || [[ $mcver == "1.20.1" ]]; then
   flavors+=("V" "Vanilla (${mcver})")
 fi
 
@@ -558,41 +522,33 @@ if [[ $? == 0 ]]; then
     F)
       # https://fabricmc.net/use/
       flavor="Fabric"
-      url="https://maven.fabricmc.net/net/fabricmc/fabric-installer/1.0.0/fabric-installer-1.0.0.jar"
+      url="https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.11.2/fabric-installer-0.11.2.jar"
       jarname="fabric-server-launch.jar"
       switches="server -mcversion ${mcver} -downloadMinecraft"
       ;;
     R)
       # https://files.minecraftforge.net/net/minecraftforge/forge/
       flavor="Forge"
-      if [[ $mcver == "1.21" ]]; then
-        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.21-51.0.26/forge-1.21-51.0.26-installer.jar"
-      elif [[ $mcver == "1.20.6" ]]; then
-        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.6-50.1.12/forge-1.20.6-50.1.12-installer.jar"
-      elif [[ $mcver == "1.20.4" ]]; then
-        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.4-49.1.0/forge-1.20.4-49.1.0-installer.jar"
-      elif [[ $mcver == "1.20.2" ]]; then
-        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.2-48.1.0/forge-1.20.2-48.1.0-installer.jar"
-      elif [[ $mcver == "1.20.1" ]]; then
-        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.1-47.3.1/forge-1.20.1-47.3.1-installer.jar"
+      if [[ $mcver == "1.20.1" ]]; then
+        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.1-47.2.1/forge-1.20.1-47.2.1-installer.jar"
       elif [[ $mcver == "1.19.4" ]]; then
-        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.19.4-45.3.0/forge-1.19.4-45.3.0-installer.jar"
+        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.19.4-45.1.0/forge-1.19.4-45.1.0-installer.jar"
       elif [[ $mcver == "1.19.3" ]]; then
         url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.19.3-44.1.23/forge-1.19.3-44.1.23-installer.jar"
       elif [[ $mcver == "1.19.2" ]]; then
-        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.19.2-43.3.13/forge-1.19.2-43.3.13-installer.jar"
+        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.19.2-43.2.1/forge-1.19.2-43.2.1-installer.jar"
       elif [[ $mcver == "1.19" ]]; then
-        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.19-41.1.0/forge-1.19-41.1.0-installer.jar"
+        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.19-41.0.110/forge-1.19-41.0.110-installer.jar"
       elif [[ $mcver == "1.18.2" ]]; then
-        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.2-40.2.21/forge-1.18.2-40.2.21-installer.jar"
+        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.2-40.1.45/forge-1.18.2-40.1.45-installer.jar"
       elif [[ $mcver == "1.18.1" ]]; then
-        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.1-39.1.2/forge-1.18.1-39.1.2-installer.jar"
+        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.1-39.0.85/forge-1.18.1-39.0.85-installer.jar"
       elif [[ $mcver == "1.18" ]]; then
         url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.18-38.0.17/forge-1.18-38.0.17-installer.jar"
       elif [[ $mcver == "1.17.1" ]]; then
-        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.17.1-37.1.1/forge-1.17.1-37.1.1-installer.jar"
+        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.17.1-37.0.107/forge-1.17.1-37.0.107-installer.jar"
       else
-        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.2.42/forge-1.16.5-36.2.42-installer.jar"
+        url="https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.1.0/forge-1.16.5-36.1.0-installer.jar"
       fi
       jarname="forge-installer.jar"
       switches="--installServer ."
@@ -606,15 +562,7 @@ if [[ $? == 0 ]]; then
     P)
       # https://papermc.io/downloads
       flavor="Paper"
-      if [[ $mcver == "1.21" ]]; then
-        url="https://api.papermc.io/v2/projects/paper/versions/1.21/builds/109/downloads/paper-1.21-109.jar"
-      elif [[ $mcver == "1.20.6" ]]; then
-        url="https://api.papermc.io/v2/projects/paper/versions/1.20.6/builds/148/downloads/paper-1.20.6-148.jar"
-      elif [[ $mcver == "1.20.4" ]]; then
-        url="https://api.papermc.io/v2/projects/paper/versions/1.20.4/builds/496/downloads/paper-1.20.4-496.jar"
-      elif [[ $mcver == "1.20.2" ]]; then
-        url="https://api.papermc.io/v2/projects/paper/versions/1.20.2/builds/318/downloads/paper-1.20.2-318.jar"
-      elif [[ $mcver == "1.20.1" ]]; then
+      if [[ $mcver == "1.20.1" ]]; then
         url="https://api.papermc.io/v2/projects/paper/versions/1.20.1/builds/196/downloads/paper-1.20.1-196.jar"
       elif [[ $mcver == "1.19.4" ]]; then
         url="https://api.papermc.io/v2/projects/paper/versions/1.19.4/builds/550/downloads/paper-1.19.4-550.jar"
@@ -665,46 +613,9 @@ fi
 
 exec 3>&1
 result=$(dialog --title "Pinecraft Installer $pcver $mcver" \
-         --menu "Choose your level type:" 20 40 10 \
-         "N"       "Normal (Default)" \
-         "F"       "Super Flat" \
-         "L"       "Large Biomes" \
-         "A"       "Amplified" \
-         "S"       "Single Biome Surface" \
-       2>&1 1>&3);
-
-if [[ $? == 0 ]]; then
-  case $result in
-    N)
-      leveltype="normal"
-      ;;
-    F)
-      leveltype="flat"
-      ;;
-    L)
-      leveltype="large_biomes"
-      ;;
-    A)
-      leveltype="amplified"
-      ;;
-    S)
-      leveltype="single_biome_surface"
-      ;;
-    esac
-else
-  echo
-  echo
-  echo "Aborted."
-  echo
-  exit 1
-fi
-
-exec 3>&1
-result=$(dialog --title "Pinecraft Installer $pcver $mcver" \
          --menu "Choose your game type:" 20 40 10 \
          "S"       "Survival" \
          "C"       "Creative" \
-         "A"       "Adventure" \
        2>&1 1>&3);
 
 if [[ $? == 0 ]]; then
@@ -714,9 +625,6 @@ if [[ $? == 0 ]]; then
       ;;
     C)
       gamemode="creative"
-      ;;
-    A)
-      gamemode="adventure"
       ;;
     esac
 else
@@ -766,7 +674,6 @@ if (( $gamemem > 12000 )); then
     gamememMIN=1500
 fi
 oc_volt=0
-oc_freq=0
 oc_friendly="N/A"
 if (( $gamememMIN < 0 )); then
   dialog --title "Error" \
@@ -806,14 +713,6 @@ elif [[ "$revision" == *"c03130" ]]; then
   oc_volt=6
   oc_freq=2000
   oc_friendly="2.0 GHz"
-elif
-  [[ "$revision" == *"c04170" ]] ||
-  [[ "$revision" == *"d04170" ]]; then
-  board='Raspberry Pi 5'
-  boardnum=4
-  oc_volt_delta=250000
-  oc_freq=2400
-  oc_friendly="2.4 GHz"
 elif [[ "$revision" == *"VIM4" ]]; then
   board='Khadas VIM4'
   boardnum=3
@@ -886,9 +785,9 @@ Server User:
 $user
 
 Server Version:
-$flavor $mcver ($leveltype $gamemode)" 20 50
+$flavor $mcver ($gamemode)" 20 50
 
-if [[ ! $oc_freq == 0 ]]; then
+if [[ ! $oc_volt == 0 ]]; then
   dialog --title "Confirmation"  --yesno "\nI will be modifying ${configfile} to overclock this ${board}. I am not responsible for damage to your system, and you do this at your own risk.\n\nContinue?" 12 50
   case $? in
   1)
@@ -1270,7 +1169,7 @@ ln -s ${instdir}stop /etc/rc6.d/K01stop-pinecraft
 # Overclock
 ###############################################
 
-if [[ ! $oc_freq == 0 ]]; then
+if [[ ! $oc_volt == 0 ]]; then
   dialog --infobox "Overclocking your system..." 3 34 ; sleep 1
   datestamp=$(date +"%Y-%m-%d_%H-%M-%S")
 
@@ -1278,16 +1177,9 @@ if [[ ! $oc_freq == 0 ]]; then
 
   # Replace existing overclock settings or add new ones if none exist
 
-  if [[ ! $oc_volt == 0 ]]; then
-    /bin/sed -i -- "/over_voltage=/c\over_voltage=${oc_volt}" $configfile
-    if ! grep -q "over_voltage=" $configfile; then
-      echo "over_voltage=$oc_volt" >> $configfile
-    fi
-  elif [[ ! $oc_volt_delta == 0 ]]; then
-    /bin/sed -i -- "/over_voltage_delta=/c\over_voltage_delta=${oc_volt_delta}" $configfile
-    if ! grep -q "over_voltage_delta=" $configfile; then
-      echo "over_voltage_delta=$oc_volt_delta" >> $configfile
-    fi
+  /bin/sed -i -- "/over_voltage=/c\over_voltage=${oc_volt}" $configfile
+  if ! grep -q "over_voltage=" $configfile; then
+    echo "over_voltage=$oc_volt" >> $configfile
   fi
 
   /bin/sed -i -- "/arm_freq=/c\arm_freq=${oc_freq}" $configfile
@@ -1362,14 +1254,6 @@ if [[ -e ${instdir}server.properties ]]; then
         echo "gamemode=${gamemode}" >> ${instdir}server.properties
       fi
 
-    # Level Type (User Selected During Install)
-      # Change the value if it exists
-      /bin/sed -i "/level-type=/c\level-type=minecraft:${leveltype}" ${instdir}server.properties
-      # Add it if it doesn't exist
-      if ! grep -q "level-type=minecraft:" ${instdir}server.properties; then
-        echo "level-type=minecraft:${leveltype}" >> ${instdir}server.properties
-      fi
-
 fi
 
 ###############################################
@@ -1435,21 +1319,6 @@ chown -R $user:$user $instdir
 
   dialog --infobox "Starting the server..." 3 26 ;
   su - $user -c "/usr/bin/screen -dmS Pinecraft ${instdir}server"
-  sleep 3
-  dialog --infobox "Initializing config..." 3 26 ;
-
-  # Allow up to 30 seconds for the server to initialize. If still not, resume anyways.
-  waited_time=0
-  while [[ $waited_time -lt 30 ]]; do
-    if [[ -e ${instdir}server.properties ]]; then
-        dialog --infobox "Server is loading..." 3 26 ; # This message signifies a successful install
-        sleep 3
-        break
-    else
-        sleep 1
-        waited_time=$((waited_time + 1))
-    fi
-  done
 
 ###############################################
 # /Run the server now
